<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XQTSCatalog.xsl" ?>
<!DOCTYPE test-suite [

<!ELEMENT GroupInfo ( title, description ) >

<!ELEMENT citation-spec ( description | note | spec-URI )* >
<!ATTLIST citation-spec name NMTOKEN #REQUIRED >

<!ELEMENT citations ( citation-spec+ ) >

<!ELEMENT collection ( description, input-document+ ) >
<!ATTLIST collection Creator CDATA #REQUIRED >
<!ATTLIST collection ID NMTOKEN #REQUIRED >

<!ELEMENT comparison ( description ) >
<!ATTLIST comparison name NMTOKEN #REQUIRED >

<!ELEMENT comparisons ( comparison+ ) >

<!ELEMENT context-properties ( context-property+ ) >

<!ELEMENT context-property EMPTY >
<!ATTLIST context-property context-type ( dynamic | static ) #REQUIRED >
<!ATTLIST context-property name CDATA #REQUIRED >

<!ELEMENT contextItem ( #PCDATA ) >
<!ATTLIST contextItem role NMTOKEN #FIXED "principal-data" >

<!ELEMENT defaultCollection ( #PCDATA ) >
<!ATTLIST defaultCollection role NMTOKEN #REQUIRED >

<!ELEMENT description ( #PCDATA ) >
<!ATTLIST description last-mod NMTOKEN #IMPLIED >

<!ELEMENT expected-error ( #PCDATA ) >
<!ATTLIST expected-error input-document NMTOKEN #IMPLIED >
<!ATTLIST expected-error spec-version NMTOKENS #IMPLIED >

<!ELEMENT feature EMPTY >
<!ATTLIST feature name CDATA #REQUIRED >

<!ELEMENT features ( feature+ ) >

<!ELEMENT implementation-defined-item ( description ) >
<!ATTLIST implementation-defined-item name ID #REQUIRED >
<!ATTLIST implementation-defined-item spec ( DataModel | FuncOps | Serialization | XQuery ) #REQUIRED >

<!ELEMENT implementation-defined-items ( implementation-defined-item+ ) >

<!ELEMENT input-URI ( #PCDATA ) >
<!ATTLIST input-URI role NMTOKEN #FIXED "principal-data" >
<!ATTLIST input-URI variable ( input-context | input-context1 | input-context2 ) #REQUIRED >

<!ELEMENT input-document ( #PCDATA ) >

<!ELEMENT input-file ( #PCDATA ) >
<!ATTLIST input-file role NMTOKEN #FIXED "principal-data" >
<!ATTLIST input-file variable ( input-context | input-context1 | input-context2 | input-context3 | inputDocument | var ) #REQUIRED >

<!ELEMENT input-query EMPTY >
<!ATTLIST input-query date CDATA #REQUIRED >
<!ATTLIST input-query name ID #REQUIRED >
<!ATTLIST input-query variable NMTOKEN #FIXED "x" >

<!ELEMENT module ( #PCDATA | description )* >
<!ATTLIST module Creator CDATA #IMPLIED >
<!ATTLIST module FileName CDATA #IMPLIED >
<!ATTLIST module ID ID #IMPLIED >
<!ATTLIST module namespace CDATA #IMPLIED >

<!ELEMENT note ( #PCDATA ) >

<!ELEMENT output-file ( #PCDATA ) >
<!ATTLIST output-file compare ( Fragment | Ignore | Inspect | Text | XML ) #REQUIRED >
<!ATTLIST output-file input-document NMTOKEN #IMPLIED >
<!ATTLIST output-file spec-version NMTOKENS #IMPLIED >
<!ATTLIST output-file role NMTOKEN #FIXED "principal" >

<!ELEMENT query ( description? ) >
<!ATTLIST query date CDATA #REQUIRED >
<!ATTLIST query name NMTOKEN #REQUIRED >
<!ATTLIST query static-name NMTOKEN #IMPLIED >

<!ELEMENT reflects-resolution ( #PCDATA ) >

<!ELEMENT role ( description, note? ) >
<!ATTLIST role name NMTOKEN #REQUIRED >

<!ELEMENT roles ( role+ ) >

<!ELEMENT scenario ( description ) >
<!ATTLIST scenario name NMTOKEN #REQUIRED >

<!ELEMENT scenarios ( scenario+ ) >

<!ELEMENT schema ( description ) >
<!ATTLIST schema FileName CDATA #REQUIRED >
<!ATTLIST schema ID ID #REQUIRED >
<!ATTLIST schema uri CDATA #REQUIRED >

<!ELEMENT source ( description, note* ) >
<!ATTLIST source Creator CDATA #REQUIRED >
<!ATTLIST source FileName CDATA #REQUIRED >
<!ATTLIST source ID ID #REQUIRED >
<!ATTLIST source schema NMTOKEN #IMPLIED >

<!ELEMENT sources ( source+, schema+, collection+, module+ ) >

<!ELEMENT spec-URI ( #PCDATA ) >

<!ELEMENT spec-citation EMPTY >
<!ATTLIST spec-citation section-number NMTOKEN #REQUIRED >
<!ATTLIST spec-citation section-pointer NMTOKEN #REQUIRED >
<!ATTLIST spec-citation section-title CDATA #REQUIRED >
<!ATTLIST spec-citation spec ( DataModel | FuncOps | UseCases | XQuery ) #REQUIRED >

<!ELEMENT test-case ( contextItem | defaultCollection | description | expected-error | input-URI | input-file | input-query | module | output-file | query | reflects-resolution | spec-citation )* >
<!ATTLIST test-case Creator CDATA #REQUIRED >
<!ATTLIST test-case FilePath CDATA #REQUIRED >
<!ATTLIST test-case is-XPath2 ( false | true ) #IMPLIED >
<!ATTLIST test-case name ID #REQUIRED >
<!ATTLIST test-case scenario ( parse-error | runtime-error | standard ) #REQUIRED >

<!ELEMENT test-group ( GroupInfo | test-case | test-group )* >
<!ATTLIST test-group featureOwner CDATA #IMPLIED >
<!ATTLIST test-group is-XPath2 ( false | true ) #IMPLIED >
<!ATTLIST test-group name ID #REQUIRED >
<!ATTLIST test-group xmlns CDATA #IMPLIED >

<!ELEMENT test-suite ( test-suite-info, citations, comparisons, roles, scenarios, sources, implementation-defined-items, features, context-properties, test-group+ ) >
<!ATTLIST test-suite CatalogDesignDate NMTOKEN #REQUIRED >
<!ATTLIST test-suite ResultOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite SourceOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite XQueryFileExtension NMTOKEN #REQUIRED >
<!ATTLIST test-suite XQueryQueryOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite XQueryXFileExtension NMTOKEN #REQUIRED >
<!ATTLIST test-suite XQueryXQueryOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite version CDATA #REQUIRED >
<!ATTLIST test-suite xmlns CDATA #REQUIRED >
<!ATTLIST test-suite xmlns:xsi CDATA #REQUIRED >
<!ATTLIST test-suite xsi:schemaLocation CDATA #REQUIRED >

<!ELEMENT test-suite-info ( title, description ) >

<!ELEMENT title ( #PCDATA ) >

<!ENTITY GhcndPartition1Queries SYSTEM "cat/GhcndPartition1Queries.xml">
<!ENTITY GhcndPartition2Queries SYSTEM "cat/GhcndPartition2Queries.xml">
<!ENTITY GhcndPartition4Queries SYSTEM "cat/GhcndPartition4Queries.xml">

<!ENTITY CollectionPartition1Queries SYSTEM "cat/CollectionPartition1Queries.xml">
<!ENTITY CollectionPartition2Queries SYSTEM "cat/CollectionPartition2Queries.xml">
<!ENTITY CollectionPartition4Queries SYSTEM "cat/CollectionPartition4Queries.xml">

]>
<test-suite xmlns="http://www.w3.org/2005/02/query-test-XQTSCatalog"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            CatalogDesignDate="2003-04-03"
            version="1.0.3"
            SourceOffsetPath="./"
            ResultOffsetPath="ExpectedTestResults/"
            XQueryQueryOffsetPath="Queries/XQuery/"
            XQueryXQueryOffsetPath="Queries/XQueryX/"
            XQueryFileExtension=".xq"
            XQueryXFileExtension=".xqx"
            xsi:schemaLocation="http://www.w3.org/2005/02/query-test-XQTSCatalog XQTSCatalog.xsd">
   <test-suite-info>
      <title>VXQuery Test Suite</title>
      <description> 
         Test Suite for VXQuery. 
      </description>
   </test-suite-info>
   <citations>
      <citation-spec name="XQuery">
         <description last-mod="2007-01-23">XQuery 1.0: An XML Query Language</description>
         <spec-URI>http://www.w3.org/TR/xquery/</spec-URI>
      </citation-spec>
      <citation-spec name="FuncOps">
         <description last-mod="2007-01-23">XQuery 1.0 and XPath 2.0 Functions and Operators</description>
         <spec-URI>http://www.w3.org/TR/xpath-functions/</spec-URI>
      </citation-spec>
      <citation-spec name="DataModel">
         <description last-mod="2007-01-23">XQuery 1.0 and XPath 2.0 Data Model</description>
         <spec-URI>http://www.w3.org/TR/xpath-datamodel/</spec-URI>
      </citation-spec>
      <citation-spec name="FormalSemantics">
         <description last-mod="2007-01-23">XQuery 1.0 and XPath 2.0 Formal Semantics</description>
         <spec-URI>http://www.w3.org/TR/xquery-semantics/</spec-URI>
      </citation-spec>
      <citation-spec name="SchemaPart2">
         <description last-mod="2003-03-25">XML Schema Part 2: Datatypes</description>
         <spec-URI>http://www.w3.org/TR/xmlschema-2/</spec-URI>
      </citation-spec>
      <citation-spec name="Schema-Errata">
         <description last-mod="2003-03-25">XML Schema Errata</description>
         <note>Current practice is to have one Errata document for all parts of Schema.</note>
         <spec-URI>http://www.w3.org/2001/05/xmlschema-errata</spec-URI>
      </citation-spec>
      <citation-spec name="UseCases">
         <description last-mod="2006-07-12">XML Query Use Cases</description>
         <spec-URI>http://www.w3c.org/TR/xquery-use-cases/</spec-URI>
      </citation-spec>
      <citation-spec name="XQueryX">
         <description last-mod="2007-01-23">XML Syntax for XQuery 1.0 (XQueryX)</description>
         <spec-URI>http://www.w3.org/TR/xqueryx/</spec-URI>
      </citation-spec>
      <citation-spec name="Serialization">
         <description last-mod="2007-01-23">XSLT 2.0 and XQuery 1.0 Serialization</description>
         <spec-URI>http://www.w3.org/TR/xslt-xquery-serialization/</spec-URI>
      </citation-spec>
   </citations>
   <comparisons>
      <comparison name="XML">
         <description last-mod="2003-03-25">The XML InfoSets should be canonicalized and compared.</description>
      </comparison>
      <comparison name="Fragment">
         <description last-mod="2004-10-20">
            A 'fragment' refers to an XML based instance which has multiple top-level elements and NO XML declaration.
            The comparator for this should simply wrap the entire fragment in a container element and perform XML comparison.
         </description>
      </comparison>
      <comparison name="Text">
         <description last-mod="2003-03-25">
            Each line of non-whitespace text should match. New-line sequences
            may vary and should be neutralized. Due to issues with the XML serialization of certain characters (e.g. '&lt;'),
            it is not possible to simply compare the actual and expected results. Rather (as is the case with the 'Fragment' comparator)
            the test harness should convert the results into valid XML (by adding a container element) and perform comparison
            on the XML canonicalized versions of the results.
         </description>
      </comparison>
      <comparison name="Ignore">
         <description last-mod="2003-03-25">
            Only the presence/absence of this file is significant,
            not its content.
         </description>
      </comparison>
      <comparison name="Inspect">
         <description last-mod="2003-03-25">
            Automated comparison is not possible. the output should be
            inspected by a human.
         </description>
      </comparison>
   </comparisons>
   <roles>
      <role name="principal-data">
         <description last-mod="2003-03-25">
            This is the source that is handed in to the processor as the
            initial input sequence, setting the "evaluation context" as described in XQuery chapter 2.
         </description>
      </role>
      <role name="supplemental-data">
         <description last-mod="2003-03-25">
            These are sources that may be read by functions such as
            fn:document() as the query is evaluated.
         </description>
      </role>
      <role name="schema">
         <description last-mod="2003-03-25">
            These are schema definitions that may be referenced by sources
            or in the query.
         </description>
      </role>
      <role name="dtd">
         <description last-mod="2003-03-25">
            These are dtd definitions that may be referenced by sources
            or in the query.
         </description>
      </role>
      <role name="principal">
         <description last-mod="2003-03-25">
            This is an output (either text or XML) that will contain the
            query results. If the processor invocation sequence accepts a filename for results, this name may be
            passed, possibly prefixed by a partial directory path to allow storage of the results in a separate
            directory tree.
         </description>
      </role>
      <role name="console-log">
         <description last-mod="2003-03-25">
            This is an output (text file tagged .log) that will contain the
            captured "console" output for a command-line invocation, or equivalent messages from a harness. The
            main goal is to capture error messages that came from the processor.
         </description>
         <note>
            A test lab may choose to capture console output for every test case, in which case the presence
            of this element is a signal that the console log of this test contains messages that are significant to
            the pass/fail determination.
         </note>
      </role>
   </roles>
   <scenarios>
      <scenario name="standard">
         <description last-mod="2005-06-10">
            A query this is expected to produce valid results. Principal input should always be specified, even if the query doesn't have any PathExpr.
         </description>
      </scenario>
      <scenario name="parse-error">
         <description last-mod="2005-06-10">
            A query this is expected to raise a parsing/syntax error at query parse time. Principal input should always be specified, even if the query doesn't have any PathExpr.
         </description>
      </scenario>
      <scenario name="runtime-error">
         <description last-mod="2005-06-10">
            A query this is expected to raise a runtime error at query parse time. Runtime errors in this case include those raised by static typing rules. Principal input should always be specified, even if the query doesn't have any PathExpr.
         </description>
      </scenario>
      <scenario name="trivial">
         <description last-mod="2006-03-29">
            A query this is expected to produce valid results. Principal input should always be specified, even if the query doesn't have any PathExpr.
            The initial query returns an &lt;xqx:xquery&gt; element (Trivial Embedding of XQuery).
            This embedded query is then executed to produce the final result.
         </description>
      </scenario>
   </scenarios>
   <sources>
      <source ID="XQTSCatalog" FileName="XQTSCatalog.xml" Creator="XQuery Test Task Force"
              schema="XQTSCatalogxsd">
         <description last-mod="2005-04-14">XQuery Test Suite Catalog</description>
      </source>
      <source ID="bib2" FileName="TestSources/bib2.xml" Creator="spec-authors">
         <description last-mod="2003-03-25">Bibliography example with extra comments and PIs.</description>
      </source>
      <source ID="emptydoc" FileName="TestSources/emptydoc.xml" Creator="David Marston">
         <description last-mod="2003-03-25">Contains just a "doc" element, no comments/text/PIs.</description>
      </source>
      <source ID="fsx" FileName="TestSources/fsx.xml" Creator="Mike Rorke">
         <description last-mod="2003-03-25">Data about a filesystem represented in XML.</description>
      </source>
      <source ID="fsx_NS" FileName="TestSources/fsx_NS.xml" Creator="Mike Rorke">
         <description last-mod="2003-03-25">Data about a filesystem represented in XML with namespace-qualified names.</description>
      </source>
      <source ID="MixNS" FileName="TestSources/MixNS.xml" Creator="David Marston">
         <description last-mod="2003-03-25">Small tree with element names in mixed namespaces.</description>
         <note>Use @index to identify elements precisely.</note>
      </source>
      <source ID="nw_Customers" FileName="TestSources/nw_Customers.xml" Creator="Kuen Siew">
         <description last-mod="2003-03-25">Customer name/address file with some non-ASCII characters.</description>
      </source>
      <source ID="TopMany" FileName="TestSources/TopMany.xml" Creator="David Marston">
         <description last-mod="2003-03-25">Like TreeCompass, but with comments and PIs off the root. PI targets vary.</description>
         <note>All text nodes must have non-whitespace characters.</note>
      </source>
      <source ID="Tree1Child" FileName="TestSources/Tree1Child.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has just one child, of an abnormal name, off the center node.</description>
         <note>One attribute each on west and center.</note>
      </source>
      <source ID="Tree1Text" FileName="TestSources/Tree1Text.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has just a text node and no child element off the center node.</description>
      </source>
      <source ID="TreeCompass" FileName="TestSources/TreeCompass.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A tree intended to allow many kinds of path expressions.</description>
         <note>Need multiple attributes on center, west, and south, plus @mark scattered around.</note>
         <note>Mix of text and element children in many places, but east should have only a text node.</note>
         <note>All text nodes must have non-whitespace characters.</note>
         <note>Top element is far-north.</note>
      </source>
      <source ID="TreeEmpty" FileName="TestSources/TreeEmpty.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has just one "south" element at the top, bearing one "mark" attribute.</description>
      </source>
      <source ID="TreeRepeat" FileName="TestSources/TreeRepeat.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has center elements off the real center node.</description>
         <note>Use @mark to distinguish center elements.</note>
         <note>"Real" center must have multiple element children, some with duplicate names (south-east).</note>
         <note>Repeating attribute names used, including same name on elements of the same name.</note>
         <note>Comments and text nodes are strewn about. All text nodes must have non-whitespace characters.</note>
      </source>
      <source ID="TreeStack" FileName="TestSources/TreeStack.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has several "south" elements, some stacked within each other.</description>
         <note>Use "mark" attributes at several levels and on all south elements.</note>
      </source>
      <source ID="TreeTrunc" FileName="TestSources/TreeTrunc.xml" Creator="David Marston">
         <description last-mod="2003-03-25">A "compass" tree that has no content at all in center or west, no attributes anywhere.</description>
      </source>
      <source ID="xq311A" FileName="TestSources/xq311A.xml" Creator="David Marston">
         <description last-mod="2003-03-25">Data that fits first example in XQuery 3.11.</description>
      </source>
      <source ID="xq311B" FileName="TestSources/xq311B.xml" Creator="David Marston">
         <description last-mod="2003-03-25">Data that fits later examples in XQuery 3.11.</description>
      </source>
      <source ID="DupNode" FileName="TestSources/DupNode.xml" Creator="Andreas Behm">
         <description last-mod="2005-04-26">Simple document with all node kinds</description>
      </source>
      <source ID="inscope" FileName="TestSources/inscope.xml" Creator="Andreas Behm">
         <description last-mod="2005-08-26">Simple document with namespaces</description>
      </source>
      <source ID="nsmode" FileName="TestSources/nsmode.xml" Creator="Andreas Behm">
         <description last-mod="2005-04-26">Source document for namespace copy modes</description>
      </source>
      <source ID="works" FileName="TestSources/works.xml" Creator="Carmelo Montanez">
         <description last-mod="2005-03-04">Data for various NIST tests</description>
      </source>
      <source ID="examples" FileName="TestSources/examples.xml" Creator="Carmelo Montanez"
              schema="examplesxsd">
         <description last-mod="2006-05-19">Data for fn-data-1 test.</description>
      </source>
      <source ID="works-mod" FileName="TestSources/works-mod.xml" Creator="Carmelo Montanez">
         <description last-mod="2005-03-04">Data for various NIST tests (abbreviated, unabbreviated syntax)</description>
      </source>
      <source ID="lang" FileName="TestSources/lang.xml" Creator="Carmelo Montanez">
         <description last-mod="2005-10-19">Data for fn:lang tests.</description>
      </source>
      <source ID="staff" FileName="TestSources/staff.xml" Creator="Carmelo Montanez">
         <description last-mod="2005-03-04">Data for various NIST tests</description>
      </source>
      <source ID="acme_corp" FileName="TestSources/acme_corp.xml"
              Creator="Ravindranath Chennoju">
         <description last-mod="2005-08-30">Source document for Function Declaration tests</description>
      </source>
      <source ID="bib" FileName="TestSources/bib.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query XMP use cases</description>
      </source>
      <source ID="reviews" FileName="TestSources/reviews.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query XMP use cases</description>
      </source>
      <source ID="books" FileName="TestSources/books.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query XMP use cases</description>
      </source>
      <source ID="prices" FileName="TestSources/prices.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query XMP use cases</description>
      </source>
      <source ID="book" FileName="TestSources/book.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query TREE use cases</description>
      </source>
      <source ID="report1" FileName="TestSources/report1.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query SEQ use cases</description>
      </source>
      <source ID="items" FileName="TestSources/items.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query RDB use cases</description>
      </source>
      <source ID="bids" FileName="TestSources/bids.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query RDB use cases</description>
      </source>
      <source ID="users" FileName="TestSources/users.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query RDB use cases</description>
      </source>
      <source ID="string" FileName="TestSources/string.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query STRING use cases</description>
      </source>
      <source ID="company-data" FileName="TestSources/company-data.xml"
              Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query STRING use cases</description>
      </source>
      <source ID="auction" FileName="TestSources/auction.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query NS use cases</description>
      </source>
      <source ID="partlist" FileName="TestSources/partlist.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query PARTS use cases</description>
      </source>
      <source ID="sgml" FileName="TestSources/sgml.xml" Creator="XML Query WG">
         <description last-mod="2005-02-11">Data for the the XML Query SGML use cases</description>
      </source>
      <source ID="atomic" FileName="TestSources/atomic.xml" Creator="Carmelo Montanez"
              schema="atomicxsd">
         <description last-mod="2005-03-08">A Schema validated xml file, that contains values for data types. Can be used by any test.</description>
      </source>
      <source ID="id-idref-dtd" FileName="TestSources/iddtd.xml" Creator="Carmelo Montanez">
         <description last-mod="2006-06-28">A DTD validated xml file, that contains data for the ID/IDREF function tests.</description>
      </source>
      <source ID="atomicns" FileName="TestSources/atomicns.xml" Creator="Carmelo Montanez">
         <description last-mod="2006-03-15">A non schema validated xml file, that contains values for data types. Can be used by any test.</description>
      </source>
      <source ID="orderData" FileName="TestSources/orderData.xml" Creator="Carmelo Montanez"
              schema="orderDataxsd">
         <description last-mod="2005-06-01">A Schema validated xml file, that contains values for some of the order by tests generated by NIST.</description>
      </source>
      <source ID="id-idref" FileName="TestSources/id.xml" Creator="Carmelo Montanez"
              schema="idxsd">
         <description last-mod="2006-05-12">Data for id and idref related functions (schema-based).</description>
      </source>
      <source ID="id-idref2" FileName="TestSources/id2.xml" Creator="Michael Kay"
              schema="idxsd">
         <description last-mod="2009-03-06">More data for id and idref related functions (schema-based).</description>
      </source>
      <source ID="SpecialTypes" FileName="TestSources/SpecialTypes.xml" Creator="Mike Rorke"
              schema="SpecialTypesXSD">
         <description last-mod="2005-06-01">A Schema validated XML file containing certain special types e.g. interleave types, union types, anySimpleType</description>
      </source>
      <source ID="QNameSource" FileName="TestSources/QName-source.xml" Creator="Mike Rorke"
              schema="QNameSourceXSD">
         <description last-mod="2005-09-28">A schema validated XML file containing QName and QName derived types.</description>
      </source>
      <source ID="notation" FileName="TestSources/notation.xml" Creator="Andreas Behm"
              schema="notationschema">
         <description last-mod="2005-10-10">A Scehma validated xml file with NOTATION elements</description>
      </source>
      <source ID="textWithSpaces" FileName="TestSources/textWithSpaces.xml"
              Creator="Joanne Tong">
         <description last-mod="2005-09-29">Data for normalize-space functions</description>
      </source>
      <source ID="XMarkAuction" FileName="TestSources/XMarkAuction.xml"
              Creator="Frans Englich">
         <description last-mod="2007-03-09">Source file generated XML Benchmark Project's xmlgen utility. See http://www.xml-benchmark.org/.</description>
      </source>
      <source ID="CPPGlobals" FileName="TestSources/CPPGlobals.xml" Creator="Frans Englich">
         <description last-mod="2007-06-27">The declarations of a C++ file described in XML.</description>
      </source>
      <source ID="MainWindow" FileName="TestSources/MainWindow.ui" Creator="Frans Englich">
         <description last-mod="2007-07-09">A description of an graphical user interface.</description>
      </source>
      <source ID="ComplexWhitespace" FileName="TestSources/ComplexWhitespace.xml"
              Creator="Frans Englich">
         <description last-mod="2007-07-09">A file containing different forms of whitespace.</description>
      </source>
      <source ID="SpaceBracket" FileName="TestSources/SpaceBracket.xml"
              Creator="Frans Englich">
         <description last-mod="2007-12-20">A file containing ' ]' as a text node.</description>
      </source>
      <source ID="HighUnicode" FileName="TestSources/HighUnicode.xml" Creator="Frans Englich">
         <description last-mod="2007-12-20">Corner case unicode codepoints.</description>
      </source>
      <source ID="HighUnicode2" FileName="TestSources/HighUnicode2.xml"
              Creator="Frans Englich">
         <description last-mod="2007-12-21">Corner case unicode codepoints, second case.</description>
      </source>
      <source ID="BCIsInvalid" FileName="TestSources/BCisInvalid.xml" Creator="Frans Englich">
         <description last-mod="2007-12-21">An element name containing 0xBC.</description>
      </source>
      <source ID="InvalidUmlaut" FileName="TestSources/InvalidUmlaut.xml"
              Creator="Frans Englich">
         <description last-mod="2007-12-27">Contains the codepoint 188 in an NCName.</description>
      </source>
      <source ID="NamespaceSuppliedInternally"
              FileName="TestSources/NamespaceSuppliedInternally.xml"
              Creator="Frans Englich">
         <description last-mod="2007-12-27">A namespace declared with a namespace declaration, as well as in the internal subset.</description>
      </source>
      <source ID="XMLIdDuplicated" FileName="TestSources/XMLIdDuplicated.xml"
              Creator="Frans Englich">
         <description last-mod="2008-01-15">An XML file which has two xml:id attributes with the same value.</description>
      </source>
      <source ID="InvalidXMLId" FileName="TestSources/InvalidXMLId.xml"
              Creator="Frans Englich">
         <description last-mod="2008-01-15">An XML file which has an invalid xml:id attribute.</description>
      </source>
      <source ID="UsingXMLId" FileName="TestSources/UsingXMLId.xml" Creator="Frans Englich">
         <description last-mod="2008-01-15">An XML file which has xml:id attributes.</description>
      </source>
      <source ID="Books2" FileName="TestSources/Books2.xml" Creator="Frans Englich">